const fs = require('fs');

const apiKey = process.env.API_KEY || ''; // Default to empty string if not set

// This script creates a JS file that makes the API key available in the browser
// by creating a mock 'process.env' object on the window.
const content = `
// This file is generated by create-env.js during the Netlify build process.
window.process = {
  ...window.process,
  env: {
    ...window.process?.env,
    API_KEY: "${apiKey}",
  },
};
`;

try {
  fs.writeFileSync('env-config.js', content);
  console.log('Successfully created env-config.js with the API key.');
} catch (err) {
  console.error('Failed to write env-config.js:', err);
  process.exit(1); // Exit with an error code to fail the build
}
